services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cart_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql-db  # Asegúrate de que esté apuntando al nombre correcto del servicio de base de datos
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: cart_api
    depends_on:
      - mysql
  
volumes:
  mysql-data:

